# Setup
title:            Cameron Wilding's Portfolio
#tagline:          'A Jekyll theme'
description:      ''
url:              http://advun.github.io
baseurl:          ""

author:
  name:           'Cam Wilding'
  url:            ""

paginate:         5
